### ISSUE TITLE
Refactor Error Handlers

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#108]
**As a** developer who used Flask RestPlus framework

**I need** to remove some unused error handlers as RestPlus take care of them for me

**So that** the code can be neat and clean

**Assumptions:**
*  Flask RestPlus framework take care of common HTTP Errors by adding decorators to APIs

**Acceptance Criteria**

```
Given error handlers are refactored
When I run `nosetests` and `behave`
Then all the tests should pass
```

**Comment by iamnwi** [comment]
@KailiDing1121 Please check PR #111. I have removed all but `DataValidationError` handler. However, if you want to add `DatabaseConnectionError` handler, go ahead.

**Comment by KailiDing1121** [comment]
@iamnwi Got it. Thanks!
