### ISSUE TITLE
Decide which database to use

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#11]
**As a** developer

**I need** a database to store App data

**So that** the App data can be persistent

**Assumptions:**
* Use database docker in a VM

**Acceptance Criteria**

```
Given ...
When ...
Then ...
```

**Comment by iamnwi** [comment]
Currently, we scaled down to two choices NoSQL and MySQL.

**Comment by iamnwi** [comment]
I would like to use MongoDB in our project. Although only @anujmenta has experience about it, it still worth us making a shot as I see it a chance to learn a new thing. Besides, I think we're not going to deal with too much data in this project. So the performance with MongoDB should be okay. What do you guys think?

**Comment by KailiDing1121** [comment]
I vote for MongoDB. Wanna try something new, and NoSQL is more "agile".

**Comment by reneesun** [comment]
Glad to try MongoDB. It's a good opportunity for me to learn NoSQL.

**Comment by anujmenta** [comment]
It is settled then! Let us use MongoDB for this use case. We all get to learn a lot from the course this way
