### ISSUE TITLE
Write App skeleton 

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#13]
**As a** developer

**I need** a skeleton to start my coding

**So that** there will be fewer conflicts and code will be more consistent

**Assumptions:**
* Create a `models.py` file for the Promotion class which will wrap all DB operations
* Create a `service.py` file which will contain all Controller functions
* Set up the config file `setup.cfg`
* Set up DB connection
* Create `tests` folder to contain tests
* Create `service` folder to contain `models.py` and `service.py`
* Write an example to show how to interact with DB via MongoDB Engine

**Acceptance Criteria**

```
Given cloned the project from Github
When `ssh` to the VM
Then we should see the project structure follows our assumptions.

Given we are in /vagrant/service
When we type `flask run --host=0.0.0.0`
Then we should able to visit `localhost:5000` on our host machine browser and see all the promotion codes we have are listed
```

**Comment by anujmenta** [comment]
What exactly do you mean by skeletons? Would it be the structure of the functions we intend to write in the scripts? If not, can you talk more about it?

**Comment by iamnwi** [comment]
> What exactly do you mean by skeletons? Would it be the structure of the functions we intend to write in the scripts? If not, can you talk more about it?

Sure, I added some details in this issue(in the Assumptions). Basically, I would like to a start point codebase, which is something like the Flask-demo in the previous lesson.

**Comment by reneesun** [comment]
Professor's repo may be a good start point?

**Comment by iamnwi** [comment]
> Professor's repo may be a good start point?

Yes, I think so. What I mentioned above is actually following his structure.

**Comment by iamnwi** [comment]
Set up DB connection and added start-up code(included a DB example). Please check this commit for details: https://github.com/devops-fall-2019-promotions-squad/promotions/commit/a8bfbea1bdea42316c1905937b6fb2e27ff463d0

@anujmenta Please go on refine it when you have time. I think you can define the fields of Promotion class, e.g. code, discount, ... Currently, I added a "code" field but it's a draft one. Thanks!

**Comment by iamnwi** [comment]
@anujmenta Hi Anuj, please let me know if you have the time to complete the App skeleton(define the fields of Promotion class). Currently, this issue blocks all other issues. If you're busy these days, I can finish the remaining part.
