### ISSUE TITLE
Discuss APIs(routings and params)

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#15]
**As a** developer

**I need** to know all APIs(routes and params)

**So that** I know how many APIs we will have and ensure that all teammates are on the same page. Besides, confirming details of APIs helps us to write API functions quicker.

**Assumptions:**
* We need at least 8 APIs, they are for
1. List Resources
-- `GET /promotions`

2. Read a Resource
-- `GET /promotions/{promotion-id}`

3. Create a Resource
-- `POST /promotions`
-- Data should include all fields that we need for creating a promotion

4. Update a Resource
-- `PUT /promotions/{promotion-id}`
-- Data through request payload and should include all fields(old values and new values) of a promotion

5. Delete a Resource
-- `DELETE /promotions/{promotion-id}`

6. Query Resources by some attribute of the Resource
-- `GET /promotions?promotion-code={promotion-code}`
-- Users may apply a promotion name when checkout so we need this API

7. Perform some stateful Action on the Resource
-- `POST /promotions/{promotion-id}/apply`
-- Take a list of the product prices and check if the promotion can apply to them. If so, return the new price of them. Otherwise, return the original price.
-- Motivation: By doing so, we hide the promotion logic from other teams, all they need to do is call our APIs and get a new list of product prices. Because sometimes the promotion logic may be complex(e.g. a conditional discount), although in this Sprint we will only handle a simple promotion logic(maybe a unified discount).

8. Displaying helpful information `/`
-- `GET /`
-- Display what API we have

**Acceptance Criteria**

```
Given we have discussed all the APIs
When we implement each API
Then we go back to this issue and stick to what we have discussed here.
```

**Comment by anujmenta** [comment]
So this would talk about how we structure our API's?

**Comment by iamnwi** [comment]
> So this would talk about how we structure our API's?

I think so. For example, the APIs for List All Promotions may be `GET promotions/list`.
After listing all the APIs then we know what should we do. What do you think?

**Comment by iamnwi** [comment]
For now, I think we at least will have the following APIs.
`GET /promotions` -- list all
`GET /promotions?id={id}` -- get a promotion by ID
`PUT /promotions` -- create a new promotion, data pass as a payload in the request. Data should include at least code discount, set of product ID?, promotion code?

**Comment by reneesun** [comment]
In the home work assignment **hint: You will need at least 7 stories for create, read, update, delete, list, query, and an action**. How we define ACTION?  apply the promotion on a product?

**Comment by reneesun** [comment]
> For now, I think we at least will have the following APIs.
> `GET /` -- show helpful information to users
> `GET /promotions` -- list all promotions
> `GET /promotions?id={id}` -- get a promotion by ID
> `PUT /promotions` -- create a new promotion, data pass as a payload in the request. Data should include at least code discount, set of product ID?, promotion code?
> `DELETE /promotions/id={id}` -- delete a promotion by ID
> 
> How about updating a promotion? use PUT to overwrite it or use UPDATE to partially up it?

I perfer PUT to overwrite. Easier to implement.

**Comment by iamnwi** [comment]
> In the home work assignment **hint: You will need at least 7 stories for create, read, update, delete, list, query, and an action**. How do we define ACTION? apply the promotion on a product?

For now, I come up with a couple of actions, but I doubt if they really should be treated as an action or if they're needed.
`/promotions/{id}/deactivate` & `/promotions/{id}/activate` but we have delete and create
`/promotions/{id}/add-product?id={product-id}` & `/promotions/{id}/remove-product?id={product-id}` but we have create
`/promotions/{id}/contains?id={product-id}` but we can also implement it as a query `GET /promotions?product-id={product-id}` which returns a list of promotions that contain a given product.

**Comment by iamnwi** [comment]
For the action part, maybe we can have the following actions:

1. `GET /promotions/rank` to rank promotions by usage

- This helps us spot out useful promotions. However, if we take this, we have to add a usage count field to our promotion model.

2. `GET /promotions/{promotion-id}/apply?product-id={list-of-id}` to return the price of each given product(maybe products in a cart) after using this promotion

- By doing so, we hide the promotion logic from other teams, all they need to do is call our APIs and get a new list of product prices. Because sometimes the promotion logic may be complex(e.g. a conditional discount), although in this Sprint we will only handle a simple promotion logic(maybe a unified discount).
- We can use `POST` instead of `GET`.

**Comment by iamnwi** [comment]
After an offline discussion, our action will be `POST /promotions/{promotion-id}/apply` which take a list of the product price and check if the promotion can apply to them. If so, return the new price of them. Otherwise, return the original price.

**Comment by reneesun** [comment]
I think we are quite clear about all the APIs. I suggest moving this issue to done.

**Comment by iamnwi** [comment]
> I think we are quite clear about all the APIs. I suggest moving this issue to done.

Sure!

**Comment by iamnwi** [comment]
I updated point 4(Update a Resource) in Assumptions. I changed it from`POST /promotions` to `POST /promotions/{promotion-id}` as I think we need a promotion-id since we're updating a particular promotion.

**Comment by KailiDing1121** [comment]
Should we use `PATCH` instead of `POST` in point 4 for updating?

**Comment by iamnwi** [comment]
> Should we use `PATCH` instead of `POST` in point 4 for updating?

Yes, you're right. I went back to our class slides and notice that we should use `PUT` or `PATCH` for our update API. However, I also notice this following point from slides:
> PUT and PATCH (update) operations modify existing resources. (PUT is more common)

Maybe we should use a `PUT`? As it is idempotent but `PATCH` isn't.
`PUT` pass all the fields to API even we only change one of them.
`PATCH` only pass the fields we change.
What do you think?@KailiDing1121

**Comment by KailiDing1121** [comment]
Yeah I agree. In [this post](https://restfulapi.net/http-methods/) it says 
> Support for PATCH in browsers, servers, and web application frameworks is not universal. IE8, PHP, Tomcat, Django, and lots of other software has missing or broken support for it.

So let's use `PUT` :smirk:
