### ISSUE TITLE
Enable IBM Cloud Service for our product

### ISSUE THREAD

**Issue by anujmenta** [devops-fall-2019-promotions-squad/promotions#46]
**As a** developer

**I need** a cloud service

**So that** we can deploy our service on it

**Assumptions:**
* IBM Could service is used
* Cloud Foundry is used
* URL `nyu-promotion-service-f19.mybluemix.net`

**Acceptance Criteria**

```
Given the cloud service is enabled for our promotion product 
When we visit "www.nyu-promotion-service-f19.mybluemix.net"
Then we should able to see the promotion service
```

**Comment by iamnwi** [comment]
Should figure out a way to connect our MongoDB
