### ISSUE TITLE
Define formats to ignore

### ISSUE THREAD

**Issue by reneesun** [devops-fall-2019-promotions-squad/promotions#6]
**As a** developer

**I need** a .gitignore file

**So that** I can keep unwanted files out of my repo.

**Assumptions:**
* There are python and vagrant autogenerated files that needs to be ignored.

**Acceptance Criteria**

```
Given the repo
When .gitignore file is created
Then unwanted files don't appear in the repo.
```

**Comment by anujmenta** [comment]
The format looks pretty clean. It looks good to me!
