### ISSUE TITLE
Modify Vagrant file to support BDD test

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#70]
**As a** developer

**I need** a dev environment that supports BDD test

**So that** I can run BDD test

**Assumptions:**
* Add dependencies for BDD testing, e.g. ChromeDriver

**Acceptance Criteria**

```
Given I'm in the dev VM
When I run command behave
Then the BDD test should run successfully
```

**Comment by reneesun** [comment]
I see professor's update about using ChromeDriver. How about we use ChromeDriver in headless mode instead of PhantomJS?

**Comment by iamnwi** [comment]
> I see professor's update about using ChromeDriver. How about we use ChromeDriver in headless mode instead of PhantomJS?

Agree.
