### ISSUE TITLE
Define promotion structure

### ISSUE THREAD

**Issue by iamnwi** [devops-fall-2019-promotions-squad/promotions#8]
**As a** Product owner

**I need** a structure for every promotion we define

**So that** we can customize and edit promotions seamlessly. 

**Assumptions:**
* Every product in the platform has a unique identifier
* Every promotion is temporary only, which means it has a start date and an end date.
* Every promotion has a set of stakeholders who can edit or modify the promotion after it is released.

**Acceptance Criteria**

```
Given the assumptions
When all of them are catered to
Then accept the structure and modify build other methods in order to accommodate the structure of the promotion,
```
**Final structure of a promotion**
- A promotion has a set of product ids which it CAN be applied to. (ex. [121, 122, 123]) and it should throw an error if it is applied to any other product.
- A promotion should have the percentage of discount that is being allowed on the product. One way to add more customization would be to allow different percentages for different products. ex. discount = 10% or discount = {'121':10%, '122':15%, '123':5%}
- A promotion should have an expiry date which determines the date after which it would be rendered useless.
- A promotion should have a list of ids of stakeholders who are the only ones eligible to modify the promotion(although, since there is no team/model for a stakeholder, we can ignore this)
- A promotion should also have a start date which would determine when a user can start using the promotion.
- A promotion will need a promotion code for the users to use it during checkout.

**Comment by anujmenta** [comment]
As a product owner, I added the core assumptions and working criteria of a promotion.

**Comment by anujmenta** [comment]
Here is how I think a promotion should look:
- A promotion has a set of product ids which it CAN be applied to. (ex. [121, 122, 123]) and it should throw an error if it is applied to any other product. 
- A promotion should have the percentage of discount that is being allowed on the product. One way to add more customization would be to allow different percentages for different products. ex. discount = 10% or discount = {'121':10%, '122':15%, '123':5%}
- A promotion should have an expiry date which determines the date after which it would be rendered useless. 
- A promotion should have a list of ids of stakeholders who are the only ones eligible to modify the promotion(although, since there is no team/model for a stakeholder, we can ignore this)
- A promotion should also have a start date which would determine when a user can start using the promotion.

These are the ones I thought about, what do you guys think?

**Comment by KailiDing1121** [comment]
Looks pretty good. However, I think now the promotion is basically discount on certain items. I think we can add more types of promotions. For example, we can have promotions like *buy 2 get 3*, *50% on second one*. And in this case, a promotion should also have a type indicating which kind of promotion it is, and promotion details. I think it also makes our app more extensible.

**Comment by iamnwi** [comment]
Looks good! One thing, do we need to add a field for the *Code of Promotion*? For example *SAVE15*. In this way, the merchant may attach this code to do their promotion and users can apply this code when they checkout.

**Comment by anujmenta** [comment]
> Looks good! One thing, do we need to add a field for the _Promotion Code_? For example _SAVE15_. In this way, the merchant may attach this code to do their promotion and users can apply this code when they checkout.

Yes! We def need to. Thanks for pointing that out.

**Comment by iamnwi** [comment]
LGTM. For the discount field problem, I think we actually can start from a simple discount promotion first then extend this feature accordingly to MVP(Minimal Viable Product). In this way, we can make progress quickly and then iterate it. However, even we have a customized discount field, I think adding a promotion type can be a good thing.

**Comment by iamnwi** [comment]
Sorry to comment on a closed issue, but could you show the structure formally? For example:
```
promotion: {
  field_1: integer(restriction 1, restriction 2, ...)
  field_2: string(letters)
  field_3: string(mixed letters and digits)
  field_4: {a: b, c:d, ...}
  ...
}
```

Besides, I will suggest that at any given time, we only have one active promotion with a particular code. e.g. Promotion-1(from 2019-10-1 to 2019-10-3 with code SAVE15) and Promotion-2(from 2019-10-2 to 2019-10-5 with code SAVE15) is not okay, but Promotion-1(from 2019-10-1 to 2019-10-3 with code SAVE15) and Promotion-2(from 2019-10-4 to 2019-10-6 with code SAVE15) is okay.
